/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RoomsRoomIdImport } from './routes/rooms/$roomId'

// Create Virtual Routes

const WishlistsLazyImport = createFileRoute('/wishlists')()
const RoomsIndexLazyImport = createFileRoute('/rooms/')()
const HostingIndexLazyImport = createFileRoute('/hosting/')()
const HostingListingIndexLazyImport = createFileRoute('/hosting/listing/')()

// Create/Update Routes

const WishlistsLazyRoute = WishlistsLazyImport.update({
  path: '/wishlists',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/wishlists.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsIndexLazyRoute = RoomsIndexLazyImport.update({
  path: '/rooms/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rooms/index.lazy').then((d) => d.Route))

const HostingIndexLazyRoute = HostingIndexLazyImport.update({
  path: '/hosting/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hosting/index.lazy').then((d) => d.Route))

const RoomsRoomIdRoute = RoomsRoomIdImport.update({
  path: '/rooms/$roomId',
  getParentRoute: () => rootRoute,
} as any)

const HostingListingIndexLazyRoute = HostingListingIndexLazyImport.update({
  path: '/hosting/listing/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/hosting/listing/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/wishlists': {
      id: '/wishlists'
      path: '/wishlists'
      fullPath: '/wishlists'
      preLoaderRoute: typeof WishlistsLazyImport
      parentRoute: typeof rootRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdImport
      parentRoute: typeof rootRoute
    }
    '/hosting/': {
      id: '/hosting/'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/hosting/listing/': {
      id: '/hosting/listing/'
      path: '/hosting/listing'
      fullPath: '/hosting/listing'
      preLoaderRoute: typeof HostingListingIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  WishlistsLazyRoute,
  RoomsRoomIdRoute,
  HostingIndexLazyRoute,
  RoomsIndexLazyRoute,
  HostingListingIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wishlists",
        "/rooms/$roomId",
        "/hosting/",
        "/rooms/",
        "/hosting/listing/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wishlists": {
      "filePath": "wishlists.lazy.tsx"
    },
    "/rooms/$roomId": {
      "filePath": "rooms/$roomId.tsx"
    },
    "/hosting/": {
      "filePath": "hosting/index.lazy.tsx"
    },
    "/rooms/": {
      "filePath": "rooms/index.lazy.tsx"
    },
    "/hosting/listing/": {
      "filePath": "hosting/listing/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
